/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author clavi
 */
public class VentEstados extends javax.swing.JFrame {

    /**
     * Creates new form VentEstados
     */
    public VentEstados() {
        initComponents();
        setTitle("Simulador SO");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProcesos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextBloqueado = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextEjucucion = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextNuevo = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextTerminado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextListo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRecursos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButtonEjecutar = new javax.swing.JButton();
        jButtonCrearP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tamaño(kB)", "Hilo", "Recurso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProcesos);

        jLabel1.setText("Nuevo");

        jTextBloqueado.setEditable(false);
        jTextBloqueado.setColumns(20);
        jTextBloqueado.setRows(5);
        jScrollPane3.setViewportView(jTextBloqueado);

        jTextEjucucion.setEditable(false);
        jTextEjucucion.setColumns(20);
        jTextEjucucion.setRows(5);
        jScrollPane4.setViewportView(jTextEjucucion);

        jTextNuevo.setEditable(false);
        jTextNuevo.setColumns(20);
        jTextNuevo.setRows(5);
        jScrollPane5.setViewportView(jTextNuevo);

        jTextTerminado.setEditable(false);
        jTextTerminado.setColumns(20);
        jTextTerminado.setRows(5);
        jScrollPane6.setViewportView(jTextTerminado);

        jLabel2.setText("Bloqueado");

        jTextListo.setEditable(false);
        jTextListo.setColumns(20);
        jTextListo.setRows(5);
        jScrollPane7.setViewportView(jTextListo);

        jLabel3.setText("Listo");

        jLabel4.setText("Ejecucion");

        jLabel5.setText("Terminado");

        jLabel6.setText("Estadistica de los Procesos");

        jTableRecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Recurso", "Proceso", "Ocupado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableRecursos);

        jLabel7.setText("Recursos");

        jButtonEjecutar.setText("Ejecutar");

        jButtonCrearP.setText("Crear Proceso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(128, 128, 128)
                .addComponent(jLabel3)
                .addGap(123, 123, 123)
                .addComponent(jLabel4)
                .addGap(102, 102, 102)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jButtonCrearP)
                        .addGap(67, 67, 67)
                        .addComponent(jButtonEjecutar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane6)
                        .addComponent(jScrollPane5)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEjecutar)
                    .addComponent(jButtonCrearP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JButton getjButtonCrearP() {
        return jButtonCrearP;
    }
    
    public void setjButtonCrearP(JButton jButtonCrearP) {
        this.jButtonCrearP = jButtonCrearP;
    }
    
    public JButton getjButtonEjecutar() {
        return jButtonEjecutar;
    }
    
    public void setjButtonEjecutar(JButton jButtonEjecutar) {
        this.jButtonEjecutar = jButtonEjecutar;
    }
    
    public JTable getjTableProcesos() {
        return jTableProcesos;
    }
    
    public void setjTableProcesos(JTable jTableProcesos) {
        this.jTableProcesos = jTableProcesos;
    }
    
    public JTable getjTableRecursos() {
        return jTableRecursos;
    }
    
    public void setjTableRecursos(JTable jTableRecursos) {
        this.jTableRecursos = jTableRecursos;
    }
    
    public JTextArea getjTextBloqueado() {
        return jTextBloqueado;
    }
    
    public void setjTextBloqueado(JTextArea jTextBloqueado) {
        this.jTextBloqueado = jTextBloqueado;
    }
    
    public JTextArea getjTextEjucucion() {
        return jTextEjucucion;
    }
    
    public void setjTextEjucucion(JTextArea jTextEjucucion) {
        this.jTextEjucucion = jTextEjucucion;
    }
    
    public JTextArea getjTextListo() {
        return jTextListo;
    }
    
    public void setjTextListo(JTextArea jTextListo) {
        this.jTextListo = jTextListo;
    }
    
    public JTextArea getjTextNuevo() {
        return jTextNuevo;
    }
    
    public void setjTextNuevo(JTextArea jTextNuevo) {
        this.jTextNuevo = jTextNuevo;
    }
    
    public JTextArea getjTextTerminado() {
        return jTextTerminado;
    }
    
    public void setjTextTerminado(JTextArea jTextTerminado) {
        this.jTextTerminado = jTextTerminado;
    }
    
    public void llenarTP(ArrayList<Proceso> a) {
        String matriz[][] = new String[a.size()][5];
        for (int i = 0; i < a.size(); i++) {
            matriz[i][0] = a.get(i).getId();
            matriz[i][1] = a.get(i).getNom();
            matriz[i][2] = String.valueOf(a.get(i).getTam());
            matriz[i][3] = String.valueOf(a.get(i).getHil());
            matriz[i][4] = String.valueOf(a.get(i).getRec());
        }
        jTableProcesos.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "ID", "Nombre", "Tamaño(kB)", "Hilo", "Recurso"
                }
        ));
    }
    
    public void llenarTR(ArrayList<Recurso> a) {
        String matriz[][] = new String[a.size()][3];
        for (int i = 0; i < a.size(); i++) {
            matriz[i][0] = a.get(i).getRec();
            matriz[i][1] = a.get(i).getProc();
            matriz[i][2] = String.valueOf(a.get(i).isOcu());
        }
        jTableRecursos.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Recurso", "Proceso", "Ocupado"
                }
        ));
    }
    
    public void limpiarN() {
        jTextNuevo.setText("");
    }
    
    public void limpiarL() {
        jTextListo.setText("");
    }
    
    public void limpiarE() {
        jTextEjucucion.setText("");
    }
    
    public void limpiarB() {
        jTextBloqueado.setText("");
    }
    
    public void limpiarT() {
        jTextTerminado.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearP;
    private javax.swing.JButton jButtonEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableProcesos;
    private javax.swing.JTable jTableRecursos;
    private javax.swing.JTextArea jTextBloqueado;
    private javax.swing.JTextArea jTextEjucucion;
    private javax.swing.JTextArea jTextListo;
    private javax.swing.JTextArea jTextNuevo;
    private javax.swing.JTextArea jTextTerminado;
    // End of variables declaration//GEN-END:variables
}
